[Project_Paths]
cvs_path = C:\AI Stuff\CV_Matching_AI\Data\CV\CV_Test
raw_json_path = C:\AI Stuff\CV_Matching_AI\Data\Raw_Json
clean_json_path = C:\AI Stuff\CV_Matching_AI\Data\Clean_Json
chunk_json_path = C:\AI Stuff\CV_Matching_AI\Data\Chunk_Json
embeddings_json_path = C:\AI Stuff\CV_Matching_AI\Embeddings

[CLEANING]
headers = Formación, Educación, Experiencia Profesional, Habilidades Técnicas, Habilidades Blandas, Certificaciones, Idiomas, Proyectos Relevantes

[EMBEDDINGS]
active_profile = mpnet

[EMBEDDINGS_mpnet]
model = sentence-transformers/paraphrase-multilingual-mpnet-base-v2
dim = 768

[EMBEDDINGS_minilm]
model = sentence-transformers/all-MiniLM-L6-v2
dim = 384

[EMBEDDINGS_bge]
model = BAAI/bge-small-en-v1.5
dim = 384

#Options run llama or phi
[LLM]
active_profile = phi

[LLM_phi]
model = phi3
temperature = 0.3
max_tokens = 512

[LLM_llama]
model = llama3.1
temperature = 0.3
max_tokens = 512

[VECTOR_STORE]
collection_name = cv_collection
index_type = faiss
persist_directory = r"C:/AI Stuff/CV_Matching_AI/VectorStore"

[CHUNKING]
tokenizer = dccuchile/bert-base-spanish-wwm-cased
chunk_size = 100
overlap = 20


